### ISSUE TITLE
Package is crashing because of XML Parser code

### ISSUE THREAD

**Issue by raghavsatyadev** [oiuldashov/speed_test_port#3]
```
Null check operator used on a null value
13:43:40.805  I  #0      XmlNodeWithChildren.hasElementWhere (package:xml_parser/src/xml_node.dart:1386:31)
                 #1      XmlNodeWithChildren.hasElement (package:xml_parser/src/xml_node.dart:1335:12)
                 #2      SpeedTestPort.getSettings (package:speed_test_port/speed_test_port.dart:25:14)
                 <asynchronous suspension>
```

**Comment by ia-alpatov** [comment]
Hello, @raghavsatyadev 
I am currently don't have a time to work on this library.
Could you fix this issue?
